### ISSUE TITLE
Addon fails to load after last new update

### ISSUE THREAD

**Issue by ThePatrykolus** [iamjustkoi/StudyTimeStats#28]
**Bug/Issue Description**
Addon fails to load after last new update

**To Reproduce**
1. Have old version of addon working fine
2. Let window about new version pop-up
3. Download it
4. You have broken addon now :( 

**Screenshots/Visuals**
![image](https://github.com/iamjustkoi/StudyTimeStats/assets/103375205/df87c399-41e8-4278-8a31-25225697f45b)

**System/Debug Info**
    
    Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
    Platform: Windows 10
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2023-05-30 21:55:36
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Add Hyperlink ['318752047', 2021-11-21T17:04, 'None', '']
    AwesomeTTS - Add speech to your flashcards ['1436550454', 2022-02-20T04:23, 'None', '']
    Batch Download Pictures From Google Images ['561924305', 2023-05-27T20:38, 'None', mod]
    Color Confirmation ['1084228676', 2020-03-14T13:13, 'None', '']
    Customize Keyboard Shortcuts ['24411424', 2022-06-29T08:13, 'None', mod]
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-28T04:21, 'None', '']
    More Decks Stats and Time Left ['1556734708', 2022-10-09T14:05, 'None', '']
    Review Heatmap ['1771074083', 2022-06-30T03:43, 'None', '']
    Study Time Stats ['1247171202', 2023-05-26T19:39, 'None', '']
    True Retention ['613684242', 2017-11-19T21:43, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1084228676 1247171202 1374772155 1436550454 1556734708 1771074083 24411424 318752047 561924305 613684242
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    

**Additional Context**
cannot think of any

**Comment by iamjustkoi** [comment]
Ope, my bad, keep forgetting Anki also runs older Python versions. 

Sorry about that! Will defs be making a new test case for this in the future, now.

Should be fixed and scheduled for the next release! Will try and send it out in a little bit.

> **Additional Context**
> cannot think of any

Haha, sounds good, and thanks a bunch for reporting this!

**Comment by ThePatrykolus** [comment]
Thank you very much for quick response! Therefore I am updating my python version :) 
Have a good day!

**Comment by iamjustkoi** [comment]
Should now be fixed with the latest patch!

> Thank you very much for quick response! 
> Have a good day!

You bet! Thanks, same to you! 😄

**Comment by ThePatrykolus** [comment]
Thank you, sir.
Unfortunately the bug persists after update.
I reinstalled it but it didn't help.
Error message has changed though:
![image](https://github.com/iamjustkoi/StudyTimeStats/assets/103375205/3414116e-0680-4204-8d12-6f8e0c97b992)

**Comment by iamjustkoi** [comment]
Oh boy, my bad. 

Should now be fixed with the latest new* patch, hopefully!

**Comment by ThePatrykolus** [comment]
Thank you once again, it solved the problem.
