### ISSUE TITLE
Add-On Not Working on Startup (Qt5)

### ISSUE THREAD

**Issue by jerryjs2** [iamjustkoi/StudyTimeStats#47]
**Bug/Issue Description**
When I start Anki, the add-on fails on startup. This started on the evening of 1/28 CST 

**To Reproduce**
Steps to reproduce:

**Screenshots/Visuals**
<img width="652" alt="Screenshot 2024-01-30 at 4 48 20 AM" src="https://github.com/iamjustkoi/StudyTimeStats/assets/92757182/b7108257-62cb-43dc-9553-850bee69d8b3">

**System/Debug Info**
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 5.14.2 PyQt 5.14.1
Platform: macOS-13.2.1-x86_64-i386-64bit

When loading Study Time Stats:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/Users/jerry/Library/Application Support/Anki2/addons21/1247171202/__init__.py", line 8, in <module>
    from .src import toolbar
  File "/Users/jerry/Library/Application Support/Anki2/addons21/1247171202/src/toolbar.py", line 12, in <module>
    from .options import TimeStatsOptionsDialog
  File "/Users/jerry/Library/Application Support/Anki2/addons21/1247171202/src/options.py", line 53, in <module>
    from ..res.ui.Qt5.cell_item import Ui_CellWidget
  File "/Users/jerry/Library/Application Support/Anki2/addons21/1247171202/res/ui/Qt5/cell_item.py", line 11, in <module>
    from PyQt6 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PyQt6'

**Additional Context**
Any other context that might seem important.

**Comment by iamjustkoi** [comment]
Aw, shoot, figured I could have the two versions intermingle but might be a simple fix I can push out real quick.

Thanks for the report!

**Comment by iamjustkoi** [comment]
Fixed in the most recent patch (v2.1.1), thanks again!

**Comment by jerryjs2** [comment]
Hi, unfortunately the issue is still persisting, and the add-on fails on startup even after updating. Here's the debug info. 

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 5.14.2 PyQt 5.14.1
Platform: macOS-13.2.1-x86_64-i386-64bit

When loading Study Time Stats:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/Users/jerry/Library/Application Support/Anki2/addons21/1247171202/__init__.py", line 8, in <module>
    from .src import toolbar
  File "/Users/jerry/Library/Application Support/Anki2/addons21/1247171202/src/toolbar.py", line 12, in <module>
    from .options import TimeStatsOptionsDialog
  File "/Users/jerry/Library/Application Support/Anki2/addons21/1247171202/src/options.py", line 53, in <module>
    from ..res.ui.Qt5.cell_item import Ui_CellWidget
  File "/Users/jerry/Library/Application Support/Anki2/addons21/1247171202/res/ui/Qt5/cell_item.py", line 554, in <module>
    from .forms import DragHandle, HoverButton, RotateButton
ModuleNotFoundError: No module named '1247171202.res.ui.Qt5.forms'

**Comment by iamjustkoi** [comment]
Ohh, shoot, this should work in the Qt5 versions, and I don't think the fix should be too difficult to fix, but I might not be able to get to it until the weekend. 
Thanks so much for reporting it in, again, though! Will try to fix this as soon as I can.

**Comment by iamjustkoi** [comment]
Should be good to go now! Sorry about the extra issues and appreciate the follow up, again!
